# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null


#Site config
title: 呆呆de小馒头

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录 
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 联系我
    url: /contact.html
  - text: 友情链接
    url: /links.html

#Author config
author:
    name: 呆呆de小馒头
    email: 
    imageLink: ../images/tm.jpg
    simpleIntro: "我想变成一个包子"
    detailIntro: "...<br>
    拼命想挽回的从前<br>在我脸上依旧清晰可见<br>最美的不是下雨天<br>是曾与你躲过雨的屋檐<br>
    ...<br>
    或许命运的签<br>只让我们遇见<br>只让我们相恋<br>
    ..."

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-weibo
    url: http://www.weibo.com/u/1705150047
  - class: icon-google-plus
    url: http://hellolinpingping5662@gmail.com
  - class: icon-github
    url: https://github.com/liuyajuntm
  - class: icon-twitter
    url: https://twitter.com/liuyajuntm
  - class: icon-facebook
    url: https://www.facebook.com/profile.php?id=100007914678289



#Links
customLinks:
  - item:
    - text: WEIBO
      url: http://www.weibo.com/u/1705150047
    message: Friends
  - item:
    - text: SISTAR
      url: http://baike.baidu.com/link?url=9Waoz1AgkOY-tXYu6TEYKcXcxip0gAm6ly0AxHw-Lnw1d8HScAkoKMcMIZuwb5IqVdN4IbuoQIqtwwlhKP59y_
    message: 其他相关链接

#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: true
  id: UA-40169250-1

#comment config